// <auto-generated />
namespace MicroServices.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialFirst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialFirst));
        
        string IMigrationMetadata.Id
        {
            get { return "201605060332103_Initial-First"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
